DROP TABLE IF EXISTS `user`;

show tables;


CREATE TABLE `user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `BIRTH_DATE` date NOT NULL,
  `EMAIL_ADDRESS` varchar(100) NOT NULL,
  `LAST_UPDATED_BY` varchar(45) NOT NULL,
  `LAST_UPDATED_DATE` datetime NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
   `SALARY` float DEFAULT NULL,
  `USER_ADDRESS_LINE_1` varchar(100) DEFAULT NULL,
  `USER_ADDRESS_LINE_2` varchar(100) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIP_CODE` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


select * from user;
truncate table user;
drop table user;

SHOW CREATE TABLE user_keys;


# this table is generated by mysql
/*
'CREATE TABLE `user_keys` (
  `PK_NAME` varchar(255) DEFAULT NULL,
  `sequence_next_hi_value` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8'
drop table user_keys;
*/

select * from user_keys;
DROP TABLE IF EXISTS `user_keys`;



DROP TABLE IF EXISTS `time_test`;

CREATE TABLE `time_test` (
  `TIME_TEST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATETIME_COLUMN` datetime DEFAULT NULL,
  `TIMESTAMP_COLUMN` timestamp NULL DEFAULT NULL,
  `DATE_COLUMN` date DEFAULT NULL,
  `TIME_COLUMN` time DEFAULT NULL,
  `SQL_DATETIME_COLUMN` datetime DEFAULT NULL,
  `SQL_TIMESTAMP_COLUMN` timestamp NULL DEFAULT NULL,
  `SQL_DATE_COLUMN` date DEFAULT NULL,
  `SQL_TIME_COLUMN` time DEFAULT NULL,
  PRIMARY KEY (`TIME_TEST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#2018-06-07 19:30:19
select * from time_test;




CREATE TABLE `bank` (
  `BANK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `ADDRESS_LINE_1` varchar(100) NOT NULL,
  `ADDRESS_LINE_2` varchar(100) NOT NULL,
  `CITY` varchar(100) NOT NULL,
  `STATE` varchar(2) NOT NULL,
  `ZIP_CODE` varchar(5) NOT NULL,
  `IS_INTERNATIONAL` tinyint(1) NOT NULL,
  `LAST_UPDATED_BY` varchar(45) NOT NULL,
  `LAST_UPDATED_DATE` datetime NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `ADDRESS_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`BANK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;


select * from bank;
drop table bank;

CREATE TABLE `BANK_CONTACT_DETAILES` (
  `BANK_ID` bigint(20) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `POSITION_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BANK_ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

select * from BANK_CONTACT_DETAILES;
drop table BANK_CONTACT_DETAILES;

