DROP TABLE IF EXISTS `user`;

show tables;


CREATE TABLE `user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `BIRTH_DATE` date NOT NULL,
  `EMAIL_ADDRESS` varchar(100) NOT NULL,
  `LAST_UPDATED_BY` varchar(45) NOT NULL,
  `LAST_UPDATED_DATE` datetime NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `USER_ADDRESS_LINE_1` varchar(100) DEFAULT NULL,
  `USER_ADDRESS_LINE_2` varchar(100) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIP_CODE` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


select * from user;
truncate table user;
drop table user;

SHOW CREATE TABLE user_keys;

select * from user_keys;
# this table is generated by mysql
/*
'CREATE TABLE `user_keys` (
  `PK_NAME` varchar(255) DEFAULT NULL,
  `sequence_next_hi_value` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8'
drop table user_keys;
*/
DROP TABLE IF EXISTS `user_keys`;



DROP TABLE IF EXISTS `time_test`;

CREATE TABLE `time_test` (
  `TIME_TEST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATETIME_COLUMN` datetime DEFAULT NULL,
  `TIMESTAMP_COLUMN` timestamp NULL DEFAULT NULL,
  `DATE_COLUMN` date DEFAULT NULL,
  `TIME_COLUMN` time DEFAULT NULL,
  `SQL_DATETIME_COLUMN` datetime DEFAULT NULL,
  `SQL_TIMESTAMP_COLUMN` timestamp NULL DEFAULT NULL,
  `SQL_DATE_COLUMN` date DEFAULT NULL,
  `SQL_TIME_COLUMN` time DEFAULT NULL,
  PRIMARY KEY (`TIME_TEST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#2018-06-07 19:30:19
select * from time_test;